### ISSUE TITLE
how to get subfield of filed 105?

### ISSUE THREAD

**Issue by Mrrkha** [lalankeba/j8583basicapp#1]
Dear Lalankeba,

Could you please help me how to get subfield of filed 105?
<field num="105" type="NUMERIC">
            <field num="1" type="NUMERIC" length="12" />
            <field num="2" type="NUMERIC" length="12" />
            <field num="3" type="NUMERIC" length="1" />
        </field>
        
        
Error 

`024-09-19T17:13:46,837 DEBUG [http-nio-8008-exec-3] c.s.i.p.ConfigParser: ISO8583 Parsing config from classpath file two.xml
2024-09-19T17:13:46,838 WARN  [http-nio-8008-exec-3] c.s.i.p.ConfigParser$1: Cannot find j8583.dtd in classpath. j8583 config files will not be validated.
2024-09-19T17:13:46,839 DEBUG [http-nio-8008-exec-3] o.a.j.l.DirectJDKLog: getResource(j8583.dtd)
2024-09-19T17:13:46,839 DEBUG [http-nio-8008-exec-3] o.a.j.l.DirectJDKLog:   Delegating to parent classloader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@2a701e5b
2024-09-19T17:13:46,839 DEBUG [http-nio-8008-exec-3] o.a.j.l.DirectJDKLog:   --> Returning 'file:/home/pbs/project/docker-Java-kubernetes-project/iso8583two/target/classes/j8583.dtd'
2024-09-19T17:13:46,841 ERROR [http-nio-8008-exec-3] c.s.i.c.CompositeField: Decoding CompositeField
java.text.ParseException: Insufficient data for NUMERIC field 0 of length 12, pos 0
        at com.solab.iso8583.parse.AlphaNumericFieldParseInfo.parse(AlphaNumericFieldParseInfo.java:46)
        at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:141)
        at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:42)
        at com.solab.iso8583.parse.AlphaNumericFieldParseInfo.parse(AlphaNumericFieldParseInfo.java:57)
        at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:601)
        at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:387)
        at com.fimi.fimi.controller.TwoController.parseIsoMessage(TwoController.java:121)
        at com.fimi.fimi.controller.TwoController.sendIsoMessage(TwoController.java:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:254)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:182)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)`

**Comment by 1234abd** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Mrrkha** [comment]
still error  "Field_105": "CompositeField[NUMERIC,NUMERIC,NUMERIC]",
